description: |
  Mikael Møller Høgsgaard \\
  PhD Student Aarhus University \\
  hogsgaard@cs.au.dk
title: Mikael Høgsgaard
logo: Untitled.png
show_downloads: false
github: false
theme: jekyll-theme-minimal