description: |
  Mikael Møller Høgsgaard \\
  PhD Student Aarhus University \\
  hogsgaard@cs.au.dk
title:  <span style="color:#267CB9; background-color:#267CB9">Mikael Møller Høgsgaard </span>
logo: Untitled.png
show_downloads: false
github: false
theme: jekyll-theme-minimal