description: My personal website
logo: Untitled.png
title: 
  text: Mikael Møller Høgsgaard
  color: black
  position: below
show_downloads: false
github: false
theme: jekyll-theme-minimal
# logo: Untitled.png
# title: Mikael Møller Høgsgaard
# show_downloads: false
# github: false
# theme: jekyll-theme-minimal
