description: |
  Mikael Møller Høgsgaard <br />
  PhD Student Aarhus University <br />
  hogsgaard@cs.au.dk
title:  <span style="color:black; background-color:white">Mikael M. Høgsgaard</span>
logo: Untitled.png
show_downloads: false
github: false
theme: jekyll-theme-minimal