description: |
  Mikael Møller Høgsgaard \\
  PhD Student Aarhus University \\
  hogsgaard@cs.au.dk
title:  <span style="color:black; background-color:white">l</span>
logo: Untitled.png
show_downloads: false
github: false
theme: jekyll-theme-minimal