# description: |
#   Mikael Møller Høgsgaard <br />
#   PhD Student Aarhus University <br />
#   hogsgaard@cs.au.dk
# # title:  <span style="color:black; background-color:white">Mikael M. Høgsgaard</span>
# logo: Untitled.png
# title: <span style="font-size:21px;"><span style="color:black; background-color:white">Mikael Møller Høgsgaard</span></span>
# show_downloads: false
# github: false
# theme: jekyll-theme-minimal

description: 
  PhD Student Aarhus University \\
  hogsgaard@cs.au.dk
title: Mikael Møller Høgsgaard
show_downloads: false
github: false
logo: Untitled.png
remote_theme: aterenin/minima-reboot